// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Foglight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Foglights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Front Fog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back Fog"
                        });
                });

            modelBuilder.Entity("Headlights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Headlights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Off"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "On"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Auto"
                        });
                });

            modelBuilder.Entity("VehicleControlPanel.Models.LocationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EndLatitude")
                        .HasColumnType("real");

                    b.Property<float>("EndLongitude")
                        .HasColumnType("real");

                    b.Property<float>("StartLatitude")
                        .HasColumnType("real");

                    b.Property<float>("StartLongitude")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LocationData");
                });

            modelBuilder.Entity("VehicleControlPanel.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Default User"
                        });
                });

            modelBuilder.Entity("VehicleControlPanel.Models.SettingsTitles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SettingsTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Driving"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Seating"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Air"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Lights"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Display"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Services"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Software"
                        });
                });

            modelBuilder.Entity("VehicleControlPanel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SettingsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleControlPanel.Models.VehicleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Foglights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HeadlightAngle")
                        .HasColumnType("integer");

                    b.Property<int>("HeadlightsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeadlightsId");

                    b.ToTable("VehicleSettings");
                });

            modelBuilder.Entity("VehicleControlPanel.Models.LocationData", b =>
                {
                    b.HasOne("VehicleControlPanel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleControlPanel.Models.User", b =>
                {
                    b.HasOne("VehicleControlPanel.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleControlPanel.Models.VehicleSettings", "VehicleSettings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("VehicleSettings");
                });

            modelBuilder.Entity("VehicleControlPanel.Models.VehicleSettings", b =>
                {
                    b.HasOne("Headlights", "Headlights")
                        .WithMany()
                        .HasForeignKey("HeadlightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headlights");
                });
#pragma warning restore 612, 618
        }
    }
}
